[package]
name = "didethresolver"
version = "0.1.0"
edition = "2021"
resolver = "2"

[profile.release]
panic = 'abort'
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tokio = { version = "1.34", features = ["macros", "rt"] }
url = { version = "2.5", features = ["serde"] }
async-trait = "0.1"
tracing = "0.1"
tracing-forest = { version = "0.1", features = ["ansi", "chrono", "env-filter"] }
tracing-subscriber = "0.3.18"
serde = { version = "1", features = ["derive"] }
jsonrpsee = { version = "0.20", features = ["macros", "server", "client-core"] }
anyhow = "1"
thiserror = "1"
argh = "0.1"
ethers = { version = "2", features = ["ws", "abigen"]}
rand = "0.8"
hex = "0.4"
smart-default = "0.7"

[dev-dependencies]
mockall = "0.12"
jsonrpsee = { version = "0.20", features = ["macros", "server", "client"] }
futures = "0.3"
tokio = { version = "1.34", features = ["macros", "rt", "time"] }
ctor = "0.2.5"
