[package]
name = "asdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libresolver = { path = "../libresolver" }
tokio.workspace = true
anyhow.workspace = true


